name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
# version: VERSION
# core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2015-06-29
version: '8.0.0-beta12'
core: '8.x'
project: 'drupal'
datestamp: 1435602053
