config.sync:
  route_name: config.sync
  base_route: config.sync
  title: 'Synchronize'

config.full:
  route_name: config.import_full
  title: 'Full Import/Export'
  base_route: config.sync

config.single:
  route_name: config.import_single
  title: 'Single Import/Export'
  base_route: config.sync

config.export_full:
  route_name: config.export_full
  title: Export
  parent_id: config.full

config.import_full:
  route_name: config.import_full
  title: Import
  parent_id: config.full

config.export_single:
  route_name: config.export_single
  title: Export
  parent_id: config.single

config.import_single:
  route_name: config.import_single
  title: Import
  parent_id: config.single
