# Schema for the migrate load plugins.

migrate.load.*:
  type: migrate_load
  label: 'Default load'

migrate.load.drupal_entity:
  type: migrate_load
  label: 'Default source'
  mapping:
    bundle_migration:
      type: string
      label: 'Bundle migration'

migrate.load.d6_term_node:
  type: migrate_load
  label: 'Default source'
  mapping:
    bundle_migration:
      type: string
      label: 'Bundle migration'
